---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:

    # https://github.com/ansible/awx/issues/8270
    - name: Configure LDAP settings
      tower_settings:
        settings:
          AUTH_LDAP_SERVER_URI: "ldaps://dc06.example.com:636"
          AUTH_LDAP_BIND_DN: "CN=AuthLDAP,OU=Service Accounts,OU=Utility,DC=example,DC=com"
          AUTH_LDAP_BIND_PASSWORD: ""
          AUTH_LDAP_START_TLS: false
          AUTH_LDAP_CONNECTION_OPTIONS:
            OPT_REFERRALS: '0'
            OPT_NETWORK_TIMEOUT: 30
          AUTH_LDAP_USER_SEARCH:
            - - "OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
              - SCOPE_SUBTREE
              - "(sAMAccountName=%(user)s)"
            - - "OU=Staff,DC=example,DC=com"
              - SCOPE_SUBTREE
              - "(sAMAccountName=%(user)s)"
          AUTH_LDAP_USER_DN_TEMPLATE:
          AUTH_LDAP_USER_ATTR_MAP:
            first_name: givenName
            last_name: sn
            email: mail
          AUTH_LDAP_GROUP_SEARCH:
            - "OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
            - SCOPE_SUBTREE
            - "(objectClass=group)"
          AUTH_LDAP_GROUP_TYPE: ActiveDirectoryGroupType
          AUTH_LDAP_GROUP_TYPE_PARAMS: {}
          AUTH_LDAP_REQUIRE_GROUP:
          AUTH_LDAP_DENY_GROUP:
          AUTH_LDAP_USER_FLAGS_BY_GROUP:
            is_superuser:
              - "CN=GG_AWX_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          AUTH_LDAP_ORGANIZATION_MAP:
            Company:
              users: "CN=GG_Infrastructure_Team_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
              admins: "CN=GG_AWX_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
              remove_admins: true
              remove_users: true
          AUTH_LDAP_TEAM_MAP:
            Servers and Storage:
              users: "CN=GG_Infrastructure_Team_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
              organization: Company
              remove: true
            AppArchitecture:
              users: "CN=GG_ArchitectureDevelopment_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
              organization: Company
              remove: true

    - name: Change LDAP Server URI
      tower_settings:
        settings:
          AUTH_LDAP_SERVER_URI: "ldaps://dc07.example.com:636"


    - name: Change LDAP Server URI
      tower_settings:
        settings:
          AUTH_LDAP_SERVER_URI: "ldaps://dc07.example.com:636"

    # - name: Set the LDAP Auth Bind Password
    #   tower_settings:
    #     name: "AUTH_LDAP_BIND_PASSWORD"
    #     value: "Password"
    #   register: result
    # 
    # - debug: var=result
