---
- name: Configure host for ansible/AWX
  hosts: localhost
  gather_facts: false
  collections:
    - awx.awx

  tasks:
    - name: with token
      tower_user:
        username: test
        first_name: FirstName
        last_name: LastName
        email: email@example.com
        password: changeme
        tower_host: https://localhost:8043
        tower_oauthtoken: LEdCpKVKc4znzffcpQL5vLG8oyeku6

    - name: with password
      tower_user:
        username: test
        first_name: FirstName
        last_name: LastName
        email: email@example.com
        password: changeme
        tower_host: https://localhost:8043
        tower_username: admin
        tower_password: password
