---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:
    - name: Create a User
      tower_user:
        first_name: Joe
        last_name: User
        username: joe
        password: "{{ 65535 | random | to_uuid }}"
        email: joe@example.org
        state: present
      register: result

    - debug: var=result
